---
VALIDATE_ALL_CODEBASE: true
APPLY_FIXES: none

ENABLE_LINTERS:
  - JAVASCRIPT_ES
  - PYTHON_BLACK
  - TYPESCRIPT_ES
  - JSON_ESLINT_PLUGIN_JSONC
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - DOCKERFILE_HADOLINT
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_SECRETLINT
