---
name: MegaLinter

permissions: read-all

on:
  workflow_dispatch:

  push:

  pull_request:
    branches:
      - main
      - dev

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: MegaLinter
        uses: oxsecurity/megalinter@5364b811bbe86576d832227be174ebc2aa0f5f49
