---
name: Publish Docker Image

permissions: read-all

on:
  workflow_dispatch:

  workflow_run:
    workflows:
      - MegaLinter
    types:
      - completed
    branches:
      - main
      - dev

jobs:
  publish_docker_image:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Fail if trying to run on main branch
        if: github.event_name == 'workflow_dispatch' && github.ref == 'main'
        run: |
          echo 'This workflow can not be manually run from the main brainch'
          exit 1

      - name: Fail if MegaLinter failed
        if: github.event.workflow_run.conclusion == 'failure'
        run: |
          echo 'MegaLinter failed, not running'
          exit 1

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{github.repository}}/leyley-bot:${{github.ref == 'main' && 'latest' || 'dev'}}
